services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  quiz-service:
    build: ./quiz-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - auth-service
      - quiz-service

volumes:
  mongo-data:
