version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    env_file:
      - ./auth-service/.env
    depends_on:
      - user-service
    networks:
      - backend

  user-service:
    build: ./user-service
    ports:
      - "3002:3002"
    env_file:
      - ./user-service/.env
    networks:
      - backend

  quiz-service:
    build: ./quiz-service
    ports:
      - "3003:3003"
    env_file:
      - ./quiz-service/.env
    depends_on:
      - user-service
    networks:
      - backend

networks:
  backend:
    driver: bridge
